import { zoomLinks } from "./zoomLinks";
import { textbooks } from "./textbooks";
import { classRooms } from "./classRooms";

export const scheduleData = [
  {
    day: "Понеділок",
    lessons: [
      [
        {
          numberLesson: 1,
          subject: "Фізика",
          zoomLink: zoomLinks.Фізика,
          textLink: textbooks.Фізика,
          classRoomLink: classRooms.Фізика,
        },
        {
          numberLesson: 1,
          subject: "Геометрія",
          zoomLink: zoomLinks.Геометрія,
          textLink: textbooks.Геометрія,
          classRoomLink: classRooms.Геометрія,
        },
      ],
      [
        {
          numberLesson: 2,
          subject: "Геометрія",
          zoomLink: zoomLinks.Геометрія,
          textLink: textbooks.Геометрія,
          classRoomLink: classRooms.Геометрія,
        },
        {
          numberLesson: 2,
          subject: "Фізика",
          zoomLink: zoomLinks.Фізика,
          textLink: textbooks.Фізика,
          classRoomLink: classRooms.Фізика,
        },
      ],
      {
        numberLesson: 3,
        subject: "Фізика",
        zoomLink: zoomLinks.Фізика,
        textLink: textbooks.Фізика,
        classRoomLink: classRooms.Фізика,
      },
      {
        numberLesson: 4,
        subject: "Фізика",
        zoomLink: zoomLinks.Фізика,
        textLink: textbooks.Фізика,
        classRoomLink: classRooms.Фізика,
      },
      {
        numberLesson: 5,
        subject: "Фізика",
        zoomLink: zoomLinks.Фізика,
        textLink: textbooks.Фізика,
        classRoomLink: classRooms.Фізика,
      },
      "Урок 6",
      "Урок 7",
      "Урок 8",
      "Урок 9",
      "Урок 10",
      "Урок 11",
    ],
  },
  {
    day: "Вівторок",
    lessons: [
      "Урок 1",
      "Урок 2",
      "Урок 3",
      "Урок 4",
      "Урок 5",
      "Урок 6",
      "Урок 7",
      "Урок 8",
      "Урок 9",
      "Урок 10",
      "Урок 11",
    ],
  },
  {
    day: "Середа",
    lessons: [
      "Урок 1",
      "Урок 2",
      "Урок 3",
      "Урок 4",
      "Урок 5",
      "Урок 6",
      "Урок 7",
      "Урок 8",
      "Урок 9",
      "Урок 10",
      "Урок 11",
    ],
  },
  {
    day: "Четвер",
    lessons: [
      "Урок 1",
      "Урок 2",
      "Урок 3",
      "Урок 4",
      "Урок 5",
      "Урок 6",
      "Урок 7",
      "Урок 8",
      "Урок 9",
      "Урок 10",
      "Урок 11",
    ],
  },
  {
    day: "П'ятниця",
    lessons: [
      "Урок 1",
      "Урок 2",
      "Урок 3",
      "Урок 4",
      "Урок 5",
      "Урок 6",
      "Урок 7",
      "Урок 8",
      "Урок 9",
      "Урок 10",
      "Урок 11",
    ],
  },
  {
    day: "Субота",
    lessons: [
      "Урок 1",
      "Урок 2",
      "Урок 3",
      "Урок 4",
      "Урок 5",
      "Урок 6",
      "Урок 7",
      "Урок 8",
      "Урок 9",
      "Урок 10",
      "Урок 11",
    ],
  },
];

export const lessonsTime = {
  lesson1: { start: "07:20", end: "08:05" },
  lesson2: { start: "08:10", end: "08:55" },
  lesson3: { start: "09:00", end: "09:45" },
  lesson4: { start: "09:50", end: "10:35" },
  lesson5: { start: "10:40", end: "11:25" },
  lesson6: { start: "11:30", end: "12:15" },
  lesson7: { start: "12:20", end: "13:05" },
  lesson8: { start: "13:10", end: "13:55" },
  lesson9: { start: "16:00", end: "16:45" },
  lesson10: { start: "18:00", end: "18:45" },
  lesson11: { start: "19:00", end: "19:45" },
};
